[package]
name = "my_web_app_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
actix-ws = "0.3.0"
futures-util = "0.3.31"
mongodb = "3.2.3"
serde = { version = "1.0.219", features = ["derive"] }
